#!/usr/bin/env python3
"""
Coze Video API Service
支持抖音、哔哩哔哩的视频信息获取和下载功能
"""

import os
import json
import logging
import subprocess
import tempfile
import shutil
from pathlib import Path
from typing import Optional, Dict, Any, List
from fastapi import FastAPI, HTTPException, Header, BackgroundTasks
from fastapi.responses import JSONResponse, FileResponse
from pydantic import BaseModel, HttpUrl, Field
import uvicorn

from config import settings

# 配置日志
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)


def format_duration_string(duration_str: str, duration_sec: Optional[int] = None) -> str:
    """
    格式化视频时长字符串
    处理 yt-dlp 返回的时长格式，确保少于 1 分钟的视频显示为 "0:XX" 格式
    
    Args:
        duration_str: yt-dlp 返回的 duration_string
        duration_sec: 可选的秒数（用于从秒数转换）
    
    Returns:
        格式化后的时长字符串（如 "0:36", "3:46", "25:40"）
    """
    if not duration_str:
        if duration_sec is not None:
            # 从秒数转换
            minutes = duration_sec // 60
            seconds = duration_sec % 60
            return f"{minutes}:{seconds:02d}"
        return ""
    
    # 检查是否只有秒数（没有冒号）
    if ':' not in duration_str:
        try:
            seconds = int(float(duration_str))
            minutes = seconds // 60
            secs = seconds % 60
            return f"{minutes}:{secs:02d}"
        except (ValueError, TypeError):
            return duration_str
    
    # 已有冒号，直接返回
    return duration_str


app = FastAPI(
    title="Coze Bilibili Uploader API",
    description="B 站 UP 主信息爬取 API 服务 - 获取 UP 主信息、视频列表、视频详情",
    version="2.0.0"
)


# ==================== 数据模型 ====================

class VideoInfoRequest(BaseModel):
    """视频信息获取请求"""
    url: str = Field(..., description="视频 URL")
    platform: str = Field(default="auto", description="平台类型", enum=["auto", "bilibili", "douyin"])
    cookie: Optional[str] = Field(default=None, description="Cookie 字符串（可选）")


class VideoDownloadRequest(BaseModel):
    """视频下载请求"""
    url: str = Field(..., description="视频 URL")
    platform: str = Field(default="auto", description="平台类型", enum=["auto", "bilibili", "douyin"])
    quality: Optional[str] = Field(default="best", description="画质", enum=["best", "4k", "1080p", "720p", "480p"])
    cookie: Optional[str] = Field(default=None, description="Cookie 字符串（可选）")


class VideoInfoResponse(BaseModel):
    """视频信息响应"""
    success: bool
    data: Optional[Dict[str, Any]] = None
    error: Optional[str] = None


class VideoDownloadResponse(BaseModel):
    """视频下载响应"""
    success: bool
    file_path: Optional[str] = None
    download_url: Optional[str] = None
    error: Optional[str] = None


class CozeWebhookRequest(BaseModel):
    """Coze Webhook 请求"""
    url: str = Field(..., description="视频 URL")
    platform: str = Field(default="auto", description="平台类型", enum=["auto", "bilibili", "douyin"])
    action: str = Field(..., description="操作类型", enum=["info", "download"])
    quality: Optional[str] = Field(default="best", description="画质", enum=["best", "4k", "1080p", "720p", "480p"])
    cookie: Optional[str] = Field(default=None, description="Cookie 字符串（可选）")


# ==================== 工具函数 ====================

def get_yt_dlp_path() -> str:
    """获取 yt-dlp 路径"""
    venv_paths = [
        "/home/ubuntu/.openclaw/workspace/projects/xhs-crawler/venv/bin/yt-dlp",
        "./venv/bin/yt-dlp",
        "/usr/local/bin/yt-dlp",
        "/usr/bin/yt-dlp"
    ]
    
    for path in venv_paths:
        if os.path.exists(path):
            return path
    
    return "yt-dlp"


def detect_platform(url: str) -> str:
    """自动检测视频平台"""
    if 'bilibili.com' in url or 'b23.tv' in url:
        return 'bilibili'
    elif 'douyin.com' in url or 'v.douyin.com' in url or 'iesdouyin.com' in url:
        return 'douyin'
    else:
        return 'unknown'


def create_cookie_file(cookie_str: str) -> str:
    """
    从 Cookie 字符串创建临时 Cookie 文件
    
    支持两种格式：
    1. Netscape 格式（多行，制表符分隔）
    2. 普通字符串格式（key=value; key2=value2）
    """
    temp_file = tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False)
    
    # 检查是否已经是 Netscape 格式
    if '\t' in cookie_str and cookie_str.startswith('#') or cookie_str.startswith('.'):
        # Netscape 格式，直接写入
        temp_file.write(cookie_str)
    else:
        # 普通格式，转换为 Netscape 格式
        temp_file.write("# Netscape HTTP Cookie File\n")
        temp_file.write("# Generated by Coze Video API\n\n")
        
        # 解析 Cookie
        cookies = cookie_str.split(';')
        for cookie in cookies:
            cookie = cookie.strip()
            if '=' in cookie:
                key, value = cookie.split('=', 1)
                key = key.strip()
                value = value.strip()
                
                # 根据平台确定域名
                domain = '.bilibili.com'  # 默认
                if 'SESSDATA' in cookie_str:
                    domain = '.bilibili.com'
                elif 'ttwid' in cookie_str or 'sessionid' in cookie_str:
                    domain = '.douyin.com'
                
                # Netscape 格式：domain flag path secure expiry name value
                temp_file.write(f"{domain}\tTRUE\t/\tFALSE\t0\t{key}\t{value}\n")
    
    temp_file.close()
    return temp_file.name


def extract_video_info(url: str, platform: str = "auto", cookie: Optional[str] = None) -> Dict[str, Any]:
    """提取视频信息"""
    import shutil
    
    yt_dlp = get_yt_dlp_path()
    
    # 自动检测平台
    if platform == "auto":
        platform = detect_platform(url)
        logger.info(f"Auto-detected platform: {platform}")
    
    cmd = [
        yt_dlp,
        "--dump-json",
        "--no-download",
    ]
    
    # 处理 Cookie
    if cookie:
        cookie_file = create_cookie_file(cookie)
        cmd.extend(["--cookies", cookie_file])
    
    cmd.append(url)
    
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=60
        )
        
        # 清理临时 Cookie 文件
        if cookie:
            try:
                os.unlink(cookie_file)
            except:
                pass
        
        if result.returncode != 0:
            logger.error(f"yt-dlp error: {result.stderr}")
            return {"error": result.stderr}
        
        return json.loads(result.stdout)
    except subprocess.TimeoutExpired:
        logger.error("Command timeout")
        return {"error": "Command timeout"}
    except json.JSONDecodeError as e:
        logger.error(f"JSON decode error: {e}")
        return {"error": f"JSON decode error: {str(e)}"}


def download_video(
    url: str,
    output_dir: str,
    quality: str = "best",
    platform: str = "auto",
    cookie: Optional[str] = None
) -> Dict[str, Any]:
    """下载视频"""
    import shutil
    
    yt_dlp = get_yt_dlp_path()
    
    # 自动检测平台
    if platform == "auto":
        platform = detect_platform(url)
    
    # 构建画质参数
    format_map = {
        "best": "bestvideo+bestaudio/best",
        "4k": "bestvideo[height<=2160]+bestaudio/best[height<=2160]",
        "1080p": "bestvideo[height<=1080]+bestaudio/best[height<=1080]",
        "720p": "bestvideo[height<=720]+bestaudio/best[height<=720]",
        "480p": "bestvideo[height<=480]+bestaudio/best[height<=480]",
    }
    
    format_str = format_map.get(quality, format_map["best"])
    
    cmd = [
        yt_dlp,
        "-f", format_str,
        "--merge-output-format", "mp4",
        "--output", os.path.join(output_dir, "%(title)s.%(ext)s"),
        "--no-mtime",
    ]
    
    # 处理 Cookie
    if cookie:
        cookie_file = create_cookie_file(cookie)
        cmd.extend(["--cookies", cookie_file])
    
    cmd.append(url)
    
    try:
        result = subprocess.run(
            cmd,
            capture_output=True,
            text=True,
            timeout=600  # 10 分钟超时
        )
        
        # 清理临时 Cookie 文件
        if cookie:
            try:
                os.unlink(cookie_file)
            except:
                pass
        
        if result.returncode != 0:
            logger.error(f"Download error: {result.stderr}")
            return {"success": False, "error": result.stderr}
        
        # 查找下载的文件
        files = list(Path(output_dir).glob("*.mp4"))
        if files:
            return {
                "success": True,
                "file_path": str(files[-1]),
                "filename": files[-1].name
            }
        
        return {"success": False, "error": "File not found after download"}
    except subprocess.TimeoutExpired:
        logger.error("Download timeout")
        return {"success": False, "error": "Download timeout"}


# ==================== API 路由 ====================

@app.get("/")
async def root():
    """健康检查"""
    return {
        "service": "Coze Video API",
        "version": "1.1.0",
        "status": "running",
        "supported_platforms": ["bilibili", "douyin"]
    }


@app.get("/health")
async def health_check():
    """健康检查端点"""
    return {"status": "healthy"}


@app.post("/api/video/info", response_model=VideoInfoResponse)
async def get_video_info(request: VideoInfoRequest):
    """
    获取视频信息
    
    - **url**: 视频 URL
    - **platform**: 平台类型 (auto, bilibili, douyin)
    - **cookie**: Cookie 字符串（可选）
    """
    logger.info(f"Getting video info: {request.url}, platform: {request.platform}")
    
    info = extract_video_info(request.url, request.platform, request.cookie)
    
    if "error" in info:
        return VideoInfoResponse(
            success=False,
            error=info["error"]
        )
    
    # 精简返回数据
    simplified_info = {
        "id": info.get("id", ""),
        "title": info.get("title", ""),
        "description": info.get("description", ""),
        "uploader": info.get("uploader", ""),
        "uploader_id": info.get("uploader_id", ""),
        "url": info.get("webpage_url", ""),
        "duration": info.get("duration", 0),
        "duration_string": format_duration_string(info.get("duration_string", ""), info.get("duration")),
        "upload_date": info.get("upload_date", ""),
        "view_count": info.get("view_count", 0),
        "like_count": info.get("like_count", 0),
        "comment_count": info.get("comment_count", 0),
        "tags": info.get("tags", []),
        "thumbnail": info.get("thumbnail", ""),
        "platform": info.get("extractor", ""),
        "formats_count": len(info.get("formats", [])),
    }
    
    return VideoInfoResponse(
        success=True,
        data=simplified_info
    )


@app.post("/api/video/download", response_model=VideoDownloadResponse)
async def download_video_endpoint(
    request: VideoDownloadRequest,
    background_tasks: BackgroundTasks
):
    """
    下载视频
    
    - **url**: 视频 URL
    - **platform**: 平台类型 (auto, bilibili, douyin)
    - **quality**: 画质 (best, 4k, 1080p, 720p, 480p)
    - **cookie**: Cookie 字符串（可选）
    """
    logger.info(f"Downloading video: {request.url}, platform: {request.platform}, quality: {request.quality}")
    
    # 创建临时目录
    temp_dir = tempfile.mkdtemp(prefix="video_download_")
    
    result = download_video(
        request.url,
        temp_dir,
        request.quality,
        request.platform,
        request.cookie
    )
    
    if not result.get("success"):
        return VideoDownloadResponse(
            success=False,
            error=result.get("error", "Unknown error")
        )
    
    # 返回文件路径
    return VideoDownloadResponse(
        success=True,
        file_path=result["file_path"],
        download_url=f"/api/files/{Path(result['file_path']).name}"
    )


@app.get("/api/files/{filename}")
async def get_file(filename: str):
    """获取下载的文件"""
    temp_dirs = list(Path("/tmp").glob("video_download_*"))
    
    for temp_dir in temp_dirs:
        file_path = temp_dir / filename
        if file_path.exists():
            return FileResponse(
                path=str(file_path),
                filename=filename,
                media_type="video/mp4"
            )
    
    raise HTTPException(status_code=404, detail="File not found")


@app.post("/api/coze/webhook")
async def coze_webhook(request: CozeWebhookRequest):
    """
    Coze Webhook 接口（支持抖音和哔哩哔哩）
    
    **请求示例**:
    ```json
    {
        "url": "https://www.bilibili.com/video/BV1xx411c7mD",
        "platform": "auto",
        "action": "info",
        "cookie": "your_cookie_string"
    }
    ```
    
    **支持的平台**:
    - bilibili: https://www.bilibili.com/video/BVxxx
    - douyin: https://www.douyin.com/video/xxx
    """
    logger.info(f"Coze webhook: {request.action} for {request.url}, platform: {request.platform}")
    
    if request.action == "info":
        info = extract_video_info(request.url, request.platform, request.cookie)
        
        if "error" in info:
            return JSONResponse({
                "success": False,
                "error": info["error"]
            })
        
        # 检测实际平台
        detected_platform = detect_platform(request.url)
        
        return JSONResponse({
            "success": True,
            "data": {
                "platform": detected_platform,
                "title": info.get("title", ""),
                "author": info.get("uploader", "") if detected_platform == "douyin" else info.get("uploader", ""),
                "duration": format_duration_string(info.get("duration_string", ""), info.get("duration")),
                "view_count": info.get("view_count", 0),
                "like_count": info.get("like_count", 0),
                "url": info.get("webpage_url", ""),
                "thumbnail": info.get("thumbnail", ""),
            }
        })
    
    elif request.action == "download":
        temp_dir = tempfile.mkdtemp(prefix="video_download_")
        
        result = download_video(
            request.url,
            temp_dir,
            request.quality,
            request.platform,
            request.cookie
        )
        
        if not result.get("success"):
            return JSONResponse({
                "success": False,
                "error": result.get("error", "Download failed")
            })
        
        return JSONResponse({
            "success": True,
            "data": {
                "filename": result.get("filename", ""),
                "file_path": result.get("file_path", ""),
                "message": "Video downloaded successfully"
            }
        })
    
    else:
        return JSONResponse({
            "success": False,
            "error": f"Unknown action: {request.action}"
        }, status_code=400)


@app.get("/api/formats")
async def list_formats(url: str, platform: str = "auto"):
    """列出视频可用格式"""
    info = extract_video_info(url, platform)
    
    if "error" in info:
        return JSONResponse({
            "success": False,
            "error": info["error"]
        })
    
    formats = info.get("formats", [])
    simplified_formats = []
    
    for fmt in formats[:20]:  # 只返回前 20 个
        simplified_formats.append({
            "format_id": fmt.get("format_id", ""),
            "format": fmt.get("format", ""),
            "ext": fmt.get("ext", ""),
            "resolution": fmt.get("resolution", ""),
            "filesize_approx": fmt.get("filesize_approx", 0),
            "tbr": fmt.get("tbr", 0),
            "vcodec": fmt.get("vcodec", ""),
            "acodec": fmt.get("acodec", ""),
        })
    
    return JSONResponse({
        "success": True,
        "data": {
            "platform": detect_platform(url),
            "title": info.get("title", ""),
            "formats": simplified_formats
        }
    })


# ==================== UP 主信息爬取 API ====================

class UploaderInfoRequest(BaseModel):
    """UP 主信息获取请求"""
    uploader_url: str = Field(..., description="UP 主主页 URL，如 https://space.bilibili.com/1815948385")
    max_videos: int = Field(default=5, description="最大获取视频数量", ge=1, le=50)
    get_details: bool = Field(default=True, description="是否获取视频详情")
    cookie: Optional[str] = Field(default=None, description="Cookie 字符串（可选）")


class UploaderInfoResponse(BaseModel):
    """UP 主信息响应"""
    success: bool
    data: Optional[Dict[str, Any]] = None
    error: Optional[str] = None


def convert_cookie_to_netscape(cookie_str: str) -> str:
    """将浏览器 Cookie 字符串转换为 Netscape 格式"""
    lines = ["# Netscape HTTP Cookie File"]
    domain = ".bilibili.com"
    
    cookies = cookie_str.split(';')
    for cookie in cookies:
        cookie = cookie.strip()
        if '=' in cookie:
            key, value = cookie.split('=', 1)
            key = key.strip()
            value = value.strip()
            # Netscape 格式：domain flag path secure expiry name value
            lines.append(f"{domain}\tTRUE\t/\tFALSE\t0\t{key}\t{value}")
    
    return '\n'.join(lines)


def run_yt_dlp_api(url: str, cookie: Optional[str] = None, extra_args: List[str] = None) -> Optional[Any]:
    """执行 yt-dlp 命令（API 版本）"""
    import subprocess
    
    yt_dlp = get_yt_dlp_path()
    cmd = [yt_dlp, "--dump-json", "--no-download"]
    
    # 处理 Cookie（转换为 Netscape 格式）
    if cookie:
        temp_cookie = tempfile.NamedTemporaryFile(mode='w', suffix='.txt', delete=False)
        netscape_cookie = convert_cookie_to_netscape(cookie)
        temp_cookie.write(netscape_cookie)
        temp_cookie.close()
        cmd.extend(["--cookies", temp_cookie.name])
    
    if extra_args:
        cmd.extend(extra_args)
    
    cmd.append(url)
    
    try:
        result = subprocess.run(cmd, capture_output=True, text=True, timeout=120)
        
        # 清理临时 Cookie 文件
        if cookie:
            try:
                os.unlink(temp_cookie.name)
            except:
                pass
        
        if result.returncode != 0:
            return {"error": result.stderr}
        
        return result.stdout
    except Exception as e:
        return {"error": str(e)}


@app.post("/api/uploader/info", response_model=UploaderInfoResponse)
async def get_uploader_info(request: UploaderInfoRequest):
    """
    获取 B 站 UP 主主页信息及视频详情
    
    **功能**:
    1. 获取 UP 主基本信息（名称、UID 等）
    2. 获取 UP 主视频列表（含封面图）
    3. 获取每个视频的详细信息（播放量、点赞数等）
    
    **适用于 Coze API 调用**
    """
    logger.info(f"Getting uploader info: {request.uploader_url}, max_videos: {request.max_videos}")
    
    # 1. 获取视频列表（不使用 flat-playlist，直接获取完整信息）
    output = run_yt_dlp_api(
        request.uploader_url,
        request.cookie,
        ["--playlist-end", str(request.max_videos)]
    )
    
    if not output or isinstance(output, dict) and "error" in output:
        return UploaderInfoResponse(
            success=False,
            error=output.get("error", "Unknown error") if isinstance(output, dict) else "Unknown error"
        )
    
    # 解析多行 JSON（每行一个视频）
    videos = []
    uploader_info = None
    logger.info(f"Raw output lines: {len(output.strip().split(chr(10))) if output else 0}")
    for line in output.strip().split('\n'):
        if line.strip():
            try:
                entry = json.loads(line)
                logger.info(f"Parsed entry: id={entry.get('id')}, title={entry.get('title', '')[:30] if entry.get('title') else 'EMPTY'}")
                
                # 跳过播放列表信息行（没有 id 字段）
                if not entry.get("id"):
                    logger.info("Skipping entry without id")
                    continue
                
                # 从第一个视频提取 UP 主信息
                if uploader_info is None:
                    uploader_info = {
                        "uploader": entry.get("uploader", ""),
                        "uploader_id": entry.get("uploader_id", ""),
                        "url": request.uploader_url,
                    }
                
                videos.append({
                    "index": len(videos) + 1,
                    "title": entry.get("title", ""),
                    "id": entry.get("id", ""),
                    "url": f"https://www.bilibili.com/video/{entry.get('id', '')}",
                    "thumbnail": entry.get("thumbnail", ""),
                    "duration_string": format_duration_string(entry.get("duration_string", ""), entry.get("duration")),
                })
            except json.JSONDecodeError as e:
                logger.error(f"JSON decode error: {e}")
                continue
    
    if not uploader_info:
        return UploaderInfoResponse(
            success=False,
            error="Failed to get uploader info"
        )
    
    result = {
        "uploader_info": uploader_info,
        "videos": videos,
        "video_count": len(videos),
    }
    
    # 2. 获取视频详情（如果需要）
    if request.get_details and videos:
        video_details = []
        for video in videos:
            output = run_yt_dlp_api(video["url"], request.cookie)
            
            if output and not isinstance(output, dict) or not (isinstance(output, dict) and output.get("error")):
                try:
                    if isinstance(output, dict):
                        continue
                    detail = json.loads(output.strip())
                    video_details.append({
                        "title": detail.get("title", ""),
                        "id": detail.get("id", ""),
                        "url": detail.get("webpage_url", ""),
                        "thumbnail": detail.get("thumbnail", ""),
                        "duration_string": format_duration_string(detail.get("duration_string", ""), detail.get("duration")),
                        "view_count": detail.get("view_count", 0),
                        "like_count": detail.get("like_count", 0),
                        "comment_count": detail.get("comment_count", 0),
                        "upload_date": detail.get("upload_date", ""),
                        "tags": detail.get("tags", []),
                        "description": detail.get("description", ""),
                    })
                except json.JSONDecodeError:
                    continue
        
        result["video_details"] = video_details
        result["details_count"] = len(video_details)
    
    return UploaderInfoResponse(
        success=True,
        data=result
    )


if __name__ == "__main__":
    uvicorn.run(
        "main:app",
        host=settings.HOST,
        port=settings.PORT,
        reload=settings.DEBUG
    )
